# Test stuff, because WingZ testing is just broken.

import test_call_before
import test_dectools_call_if2
import test_dectools_call_if
import test_dectools_call_instead
import test_dectools_call_once
import test_dectools_make_call_if
import test_dectools_make_call_instead
import test_dectools_log
import test_dectools_make_call_once
import test_dict_as_called
import test_pre_post
import test_invariants

